---
- name: Deploy Docker container from tar
  hosts: all
  become: yes
  tasks:

    - name: Copy Docker image tar to remote server
      copy:
        src: "/tmp/{{ image_tar }}"
        dest: "/tmp/{{ image_tar | basename }}"
        remote_src: yes
        mode: '0644'
        

    - name: Load Docker image from tar
      command: docker load -i /tmp/{{ image_tar | basename }}

    - name: Run Docker container
      command: docker run -d --name {{ image_name }} {{ image_name }}
      ignore_errors: true  # Optional: in case the container is already running
