---
- name: Deploy Docker container from tar
  hosts: all
  become: true
  vars:
    image_tar: /tmp/my-python-app.tar
    image_name: my-python-app

  tasks:
    - name: Load Docker image from tar
      command: docker load -i "{{ image_tar }}"

    - name: Stop and remove existing container (if any)
      shell: |
        docker rm -f "{{ image_name }}" || true

    - name: Run new Docker container
      command: docker run -d --name "{{ image_name }}" -p 5000:5000 "{{ image_name }}"
